In [2]:
import pandas as pd

In [4]:
df= pd.read_csv(r"C:\Users\adity\OneDrive\Desktop\DataAnalyst\Projects\Project5\decadal-average-death-rates-from-natural-disasters\decadal-average-death-rates-from-natural-disasters.csv")
df

,Entity,Code,Year,"Deaths per 100,000 people - Drought (decadal)","Deaths per 100,000 people - Flood (decadal)","Deaths per 100,000 people - Earthquake (decadal)","Deaths per 100,000 people - Extreme weather (decadal)","Deaths per 100,000 people - Extreme temperature (decadal)","Deaths per 100,000 people - Volcanic activity (decadal)","Deaths per 100,000 people - Wildfire (decadal)","Deaths per 100,000 people - Glacial lake outburst flood (decadal)","Deaths per 100,000 people - Dry mass movement (decadal)","Deaths per 100,000 people - Wet mass movement (decadal)","Deaths per 100,000 people - Fog (decadal)"
0,Afghanistan,AFG,1900,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,AFG,1910,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,AFG,1920,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,AFG,1930,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,1940,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3063,Zimbabwe,ZWE,1980,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3064,Zimbabwe,ZWE,1990,0.0,0.031173,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3065,Zimbabwe,ZWE,2000,0.0,0.093379,0.0,0.006625,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3066,Zimbabwe,ZWE,2010,0.0,0.119160,0.0,0.607668,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3067,Zimbabwe,ZWE,2020,0.0,0.000000,0.0,0.006152,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
df.describe()

,Year,"Deaths per 100,000 people - Drought (decadal)","Deaths per 100,000 people - Flood (decadal)","Deaths per 100,000 people - Earthquake (decadal)","Deaths per 100,000 people - Extreme weather (decadal)","Deaths per 100,000 people - Extreme temperature (decadal)","Deaths per 100,000 people - Volcanic activity (decadal)","Deaths per 100,000 people - Wildfire (decadal)","Deaths per 100,000 people - Glacial lake outburst flood (decadal)","Deaths per 100,000 people - Dry mass movement (decadal)","Deaths per 100,000 people - Wet mass movement (decadal)","Deaths per 100,000 people - Fog (decadal)"
count,3068.000000,3068.000000,3068.000000,3068.000000,3068.000000,3068.000000,3068.000000,3068.000000,3068.000000,3068.000000,3068.000000,3068.000000
mean,1960.000000,2.209648,0.184912,0.385797,0.614158,0.040321,0.165399,0.000976,0.000005,0.001209,0.015025,0.000306
std,37.422673,55.858094,3.223555,4.894098,11.354521,0.328182,6.578844,0.010835,0.000141,0.034930,0.225452,0.014403
min,1900.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1930.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1960.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1990.000000,0.000000,0.007032,0.000000,0.003016,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2020.000000,2475.928500,133.092440,226.138210,480.272800,6.101210,357.338560,0.468031,0.006044,1.853207,9.190208,0.792318

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3068 entries, 0 to 3067
Data columns (total 14 columns):
 #   Column                                                             Non-Null Count  Dtype
---  ------                                                             --------------  -----
 0   Entity                                                             3068 non-null   object
 1   Code                                                               2925 non-null   object
 2   Year                                                               3068 non-null   int64
 3   Deaths per 100,000 people - Drought (decadal)                      3068 non-null   float64
 4   Deaths per 100,000 people - Flood (decadal)                        3068 non-null   float64
 5   Deaths per 100,000 people - Earthquake (decadal)                   3068 non-null   float64
 6   Deaths per 100,000 people - Extreme weather (decadal)              3068 non-null   float64
 7   Deaths per 100,000 people - Extreme temperature (decadal)          3068 non-null   float64
 8   Deaths per 100,000 people - Volcanic activity (decadal)            3068 non-null   float64
 9   Deaths per 100,000 people - Wildfire (decadal)                     3068 non-null   float64
 10  Deaths per 100,000 people - Glacial lake outburst flood (decadal)  3068 non-null   float64
 11  Deaths per 100,000 people - Dry mass movement (decadal)            3068 non-null   float64
 12  Deaths per 100,000 people - Wet mass movement (decadal)            3068 non-null   float64
 13  Deaths per 100,000 people - Fog (decadal)                          3068 non-null   float64
dtypes: float64(11), int64(1), object(2)
memory usage: 335.7+ KB

In [10]:
df.isnull().sum()

Entity                                                                 0
Code                                                                 143
Year                                                                   0
Deaths per 100,000 people - Drought (decadal)                          0
Deaths per 100,000 people - Flood (decadal)                            0
Deaths per 100,000 people - Earthquake (decadal)                       0
Deaths per 100,000 people - Extreme weather (decadal)                  0
Deaths per 100,000 people - Extreme temperature (decadal)              0
Deaths per 100,000 people - Volcanic activity (decadal)                0
Deaths per 100,000 people - Wildfire (decadal)                         0
Deaths per 100,000 people - Glacial lake outburst flood (decadal)      0
Deaths per 100,000 people - Dry mass movement (decadal)                0
Deaths per 100,000 people - Wet mass movement (decadal)                0
Deaths per 100,000 people - Fog (decadal)                              0
dtype: int64

In [12]:
df['Code'] = df['Code'].fillna('N/A')

In [16]:
df.isnull().sum()

Entity                                                               0
Code                                                                 0
Year                                                                 0
Deaths per 100,000 people - Drought (decadal)                        0
Deaths per 100,000 people - Flood (decadal)                          0
Deaths per 100,000 people - Earthquake (decadal)                     0
Deaths per 100,000 people - Extreme weather (decadal)                0
Deaths per 100,000 people - Extreme temperature (decadal)            0
Deaths per 100,000 people - Volcanic activity (decadal)              0
Deaths per 100,000 people - Wildfire (decadal)                       0
Deaths per 100,000 people - Glacial lake outburst flood (decadal)    0
Deaths per 100,000 people - Dry mass movement (decadal)              0
Deaths per 100,000 people - Wet mass movement (decadal)              0
Deaths per 100,000 people - Fog (decadal)                            0
dtype: int64

In [18]:
df.columns = [col.replace('Deaths per 100,000 people - ', '').replace(' (decadal)', '').strip() for col in df.columns]

In [20]:
df

,Entity,Code,Year,Drought,Flood,Earthquake,Extreme weather,Extreme temperature,Volcanic activity,Wildfire,Glacial lake outburst flood,Dry mass movement,Wet mass movement,Fog
0,Afghanistan,AFG,1900,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Afghanistan,AFG,1910,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,AFG,1920,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Afghanistan,AFG,1930,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Afghanistan,AFG,1940,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3063,Zimbabwe,ZWE,1980,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3064,Zimbabwe,ZWE,1990,0.0,0.031173,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3065,Zimbabwe,ZWE,2000,0.0,0.093379,0.0,0.006625,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3066,Zimbabwe,ZWE,2010,0.0,0.119160,0.0,0.607668,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3067,Zimbabwe,ZWE,2020,0.0,0.000000,0.0,0.006152,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
df['Total Deaths per 100k'] = df.iloc[:, 3:].sum(axis=1)
df['Total Deaths per 100k']

0       0.000000
1       0.000000
2       0.000000
3       0.000000
4       0.000000
          ...
3063    0.000000
3064    0.031173
3065    0.100004
3066    0.726828
3067    0.006152
Name: Total Deaths per 100k, Length: 3068, dtype: float64

In [26]:
df.to_csv(r'C:\Users\adity\OneDrive\Desktop\DataAnalyst\Projects\Project5\deaths-by-natural-disaster.csv', index=False)